# load the required libraries

In [19]:
import pandas as pd # used for data manipulation and analysis

# load the dataset (csv), and checking the dataframe

In [20]:
df = pd.read_csv('bhatbhateni_sales.csv') # read the CSV file into a DataFrame
print(df.head()) # print the first 5 rows of the DataFrame
print(df.shape) # print the shape of the DataFrame
print(df.columns) # print the column names of the DataFrame
print("Rows:", df.shape[0]) # Number of rows
print("Columns:", df.shape[1]) # Number of columns

  TransactionID        Date CustomerID    CustomerName  \
0     TXN101590  2025-05-19   CUST1100  Sujan Shrestha
1     TXN103282  2025-03-07   CUST1005      Milan Lama
2     TXN103539  2025-10-05   CUST1130       Alina Rai
3     TXN102479  2025-11-12   CUST1057      Neha Karki
4     TXN104408  2025-10-09   CUST1005      Milan Lama

                     Branch ProductCategory           ProductName  Quantity  \
0        Pokhara - Lakeside          Bakery  Chocolate Cake Slice         2
1    Butwal - Traffic Chowk   Personal Care             Dove Soap         3
2  Bhaktapur - Suryabinayak         Apparel         Winter Jacket         4
3      Kathmandu - New Road       Household        Surf Excel 1kg         4
4    Butwal - Traffic Chowk       Beverages  Gorkha Beer (6-pack)         2

   UnitPrice  TotalAmount PaymentMethod
0     171.29       342.58        Khalti
1     149.59       448.77         eSewa
2    2794.25     11177.00        Khalti
3     399.62      1598.48          Cash
4     281.01       562.02         eSewa
(18812, 11)
Index(['TransactionID', 'Date', 'CustomerID', 'CustomerName', 'Branch',
       'ProductCategory', 'ProductName', 'Quantity', 'UnitPrice',
       'TotalAmount', 'PaymentMethod'],
      dtype='str')
Rows: 18812
Columns: 11

List the columns

In [21]:
list(df.columns) # list the column names of the DataFrame

['TransactionID',
 'Date',
 'CustomerID',
 'CustomerName',
 'Branch',
 'ProductCategory',
 'ProductName',
 'Quantity',
 'UnitPrice',
 'TotalAmount',
 'PaymentMethod']

# Data Types, and Structure

In [22]:
print(df.info()) # print the summary information of the DataFrame
print(df.describe(include='all')) # print the statistical summary of the DataFrame
print(df.dtypes) # print the data types of each column in the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 18812 entries, 0 to 18811
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    18812 non-null  str
 1   Date             18812 non-null  str
 2   CustomerID       18812 non-null  str
 3   CustomerName     18244 non-null  str
 4   Branch           18812 non-null  str
 5   ProductCategory  18530 non-null  str
 6   ProductName      18812 non-null  str
 7   Quantity         18812 non-null  int64
 8   UnitPrice        18441 non-null  float64
 9   TotalAmount      18812 non-null  float64
 10  PaymentMethod    18344 non-null  str
dtypes: float64(2), int64(1), str(8)
memory usage: 1.6 MB
None
       TransactionID        Date CustomerID CustomerName  \
count          18812       18812      18812        18244
unique          6000         365        147          116
top        TXN103822  2025-09-30   CUST1002    Alina Rai
freq               7         142        685          666
mean             NaN         NaN        NaN          NaN
std              NaN         NaN        NaN          NaN
min              NaN         NaN        NaN          NaN
25%              NaN         NaN        NaN          NaN
50%              NaN         NaN        NaN          NaN
75%              NaN         NaN        NaN          NaN
max              NaN         NaN        NaN          NaN

                       Branch ProductCategory         ProductName  \
count                   18812           18530               18812
unique                      8               8                  41
top     Kathmandu - Kupondole         Grocery  Sanitary Pads Pack
freq                     3391            3146                 502
mean                      NaN             NaN                 NaN
std                       NaN             NaN                 NaN
min                       NaN             NaN                 NaN
25%                       NaN             NaN                 NaN
50%                       NaN             NaN                 NaN
75%                       NaN             NaN                 NaN
max                       NaN             NaN                 NaN

            Quantity     UnitPrice   TotalAmount PaymentMethod
count   18812.000000  18441.000000  18812.000000         18344
unique           NaN           NaN           NaN             5
top              NaN           NaN           NaN          Cash
freq             NaN           NaN           NaN          6464
mean        2.506804    728.803530   1819.990565           NaN
std         1.114328    766.346109   2241.968350           NaN
min         1.000000     40.140000     40.610000           NaN
25%         2.000000    240.160000    488.397500           NaN
50%         3.000000    416.780000    989.000000           NaN
75%         3.000000    848.320000   2142.545000           NaN
max         4.000000   3499.280000  13997.120000           NaN
TransactionID          str
Date                   str
CustomerID             str
CustomerName           str
Branch                 str
ProductCategory        str
ProductName            str
Quantity             int64
UnitPrice          float64
TotalAmount        float64
PaymentMethod          str
dtype: object

# Detech Data Quality Issues

In [23]:
missing_count = df.isnull().sum() # count the number of missing values in each column
print(missing_count) # print the count of missing values in each column
missing_percent = (missing_count / len(df)) * 100 # calculate the percentage of missing values in each column
print(missing_percent) # print the percentage of missing values in each column  
# Combine both into one DataFrame
missing_summary = pd.DataFrame({
    "Missing Values": missing_count,
    "Percentage (%)": missing_percent.round(2)
})
print(missing_summary)

TransactionID        0
Date                 0
CustomerID           0
CustomerName       568
Branch               0
ProductCategory    282
ProductName          0
Quantity             0
UnitPrice          371
TotalAmount          0
PaymentMethod      468
dtype: int64
TransactionID      0.000000
Date               0.000000
CustomerID         0.000000
CustomerName       3.019349
Branch             0.000000
ProductCategory    1.499043
ProductName        0.000000
Quantity           0.000000
UnitPrice          1.972145
TotalAmount        0.000000
PaymentMethod      2.487774
dtype: float64
                 Missing Values  Percentage (%)
TransactionID                 0            0.00
Date                          0            0.00
CustomerID                    0            0.00
CustomerName                568            3.02
Branch                        0            0.00
ProductCategory             282            1.50
ProductName                   0            0.00
Quantity                      0            0.00
UnitPrice                   371            1.97
TotalAmount                   0            0.00
PaymentMethod               468            2.49

# Duplicated

In [24]:
duplicate_rows = df.duplicated().sum() # count the number of duplicate rows in the DataFrame

print(f"Number of duplicate rows: {duplicate_rows}") # print the number of duplicate rows in the DataFrame

Number of duplicate rows: 724

Check Duplicate Transaction IDs

In [25]:
transaction_duplicates = df["TransactionID"].duplicated().sum() # count the number of duplicate Transaction IDs in the DataFrame

print(f"Repeated Transaction IDs: {transaction_duplicates}")

# View all records with repeated Transaction IDs
df[df["TransactionID"].duplicated(keep=False)].sort_values("TransactionID")

Repeated Transaction IDs: 12812

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod
3968,TXN100000,2025-04-09,CUST1064,Sandip Khadka,Bhaktapur - Suryabinayak,Personal Care,Colgate Toothpaste,3,402.71,1208.13,Cash
8564,TXN100000,2025-04-09,CUST1064,Sandip Khadka,Bhaktapur - Suryabinayak,Bakery,Chocolate Cake Slice,4,345.66,1382.64,eSewa
2922,TXN100000,2025-04-09,CUST1064,Sandip Khadka,Bhaktapur - Suryabinayak,Personal Care,Dove Soap,3,486.58,1459.74,Khalti
1242,TXN100000,2025-04-09,CUST1064,Sandip Khadka,Bhaktapur - Suryabinayak,Bakery,Khari Biscuit Pack,2,142.38,284.76,eSewa
1986,TXN100000,2025-04-09,CUST1064,Sandip Khadka,Bhaktapur - Suryabinayak,Grocery,Sugar 1kg,4,128.86,515.44,eSewa
...,...,...,...,...,...,...,...,...,...,...,...
3532,TXN105999,2025-09-08,CUST1016,Neha Poudel,Chitwan - Bharatpur,Grocery,Salt 1kg,1,778.22,778.22,Khalti
14974,TXN105999,2025-09-08,CUST1016,Neha Poudel,Chitwan - Bharatpur,Dairy,DDC Milk 1L,1,128.33,128.33,Cash
3626,TXN105999,2025-09-08,CUST1016,NaN,Chitwan - Bharatpur,Apparel,Kids Frock,4,1553.74,6214.96,Bank Transfer
1668,TXN105999,2025-09-08,CUST1016,Neha Poudel,Chitwan - Bharatpur,Bakery,Sliced Bread,1,341.67,341.67,Debit/Credit Card
14882,TXN105999,2025-09-08,CUST1016,Neha Poudel,Chitwan - Bharatpur,Electronics,Wall Clock,4,2003.86,8015.44,Bank Transfer

Validate Total Amount

In [26]:
expected_total = df["Quantity"] * df["UnitPrice"] # Calculate expected total

incorrect_total = df[df["TotalAmount"] != expected_total] # Find mismatched rows

print("Incorrect TotalAmount rows:", len(incorrect_total))

incorrect_total.head()

Incorrect TotalAmount rows: 1821

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod
20,TXN101977,2025-07-30,CUST1008,Alina Tamang,Bhaktapur - Suryabinayak,Bakery,Khari Biscuit Pack,3,223.30,669.90,Khalti
44,TXN104729,2025-01-22,CUST1075,Deepak Magar,Butwal - Traffic Chowk,Electronics,USB Cable Type-C,4,NaN,6753.16,Cash
57,TXN101880,2025-03-26,CUST1145,Manisha Adhikari,Biratnagar - Main Road,Electronics,Wall Clock,3,3087.93,9263.79,Debit/Credit Card
65,TXN105145,2025-11-07,CUST1059,Rajesh Shrestha,Kathmandu - Kupondole,Beverages,Tea Leaves (Ilam) 250g,4,NaN,1796.84,Cash
83,TXN103825,2025-07-09,CUST1055,Rohit Poudel,Lalitpur - Pulchowk,Household,Steel Lunch Box,3,484.35,1453.05,Cash

# Remove Duplicate Rows

In [27]:
df = df.drop_duplicates() # Remove duplicate rows from the DataFrame

print("Duplicates removed successfully.") # print a success message

Duplicates removed successfully.

# Verify Duplicate Removal

In [28]:
print("Current Shape:", df.shape) # print the current shape of the DataFrame after removing duplicates  

print("Remaining Duplicates:", df.duplicated().sum()) # print the number of remaining duplicate rows in the DataFrame after removing duplicates

Current Shape: (18088, 11)
Remaining Duplicates: 0

# Fill Missing Customer Names

In [29]:
df["CustomerName"] = df["CustomerName"].fillna("Unknown") # fill missing values in the "CustomerName" column with "Unknown"

# Fill Missing Product Categories

In [30]:
# Fill missing categories using ProductName
df["ProductCategory"] = (
    df.groupby("ProductName")["ProductCategory"]
      .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else "Unknown"))
)

# Fill Missing Unit Price

In [31]:
# Fill missing UnitPrice using TotalAmount and Quantity
df["UnitPrice"] = df["UnitPrice"].fillna(
    df["TotalAmount"] / df["Quantity"]
)

# Fill Missing Payment Method

In [32]:
df["PaymentMethod"] = df["PaymentMethod"].fillna("Unknown") # fill missing values in the "PaymentMethod" column with "Unknown"

# Verify Missing Values

In [33]:
miss = df.isnull().sum() # Calculate the number of missing values in each column
print("Missing Values:")
print(miss)

Missing Values:
TransactionID      0
Date               0
CustomerID         0
CustomerName       0
Branch             0
ProductCategory    0
ProductName        0
Quantity           0
UnitPrice          0
TotalAmount        0
PaymentMethod      0
dtype: int64

# Convert Date Column

In [34]:
# Convert to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Extract useful time features
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["MonthName"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

# Display first few rows
df.head()

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod,Year,Month,MonthName,Day,Weekday
0,TXN101590,2025-05-19,CUST1100,Sujan Shrestha,Pokhara - Lakeside,Bakery,Chocolate Cake Slice,2,171.29,342.58,Khalti,2025,5,May,19,Monday
1,TXN103282,2025-03-07,CUST1005,Milan Lama,Butwal - Traffic Chowk,Personal Care,Dove Soap,3,149.59,448.77,eSewa,2025,3,March,7,Friday
2,TXN103539,2025-10-05,CUST1130,Alina Rai,Bhaktapur - Suryabinayak,Apparel,Winter Jacket,4,2794.25,11177.00,Khalti,2025,10,October,5,Sunday
3,TXN102479,2025-11-12,CUST1057,Neha Karki,Kathmandu - New Road,Household,Surf Excel 1kg,4,399.62,1598.48,Cash,2025,11,November,12,Wednesday
4,TXN104408,2025-10-09,CUST1005,Milan Lama,Butwal - Traffic Chowk,Beverages,Gorkha Beer (6-pack),2,281.01,562.02,eSewa,2025,10,October,9,Thursday

# Extract City

In [35]:
df["City"] = df["Branch"].str.split("-").str[0].str.strip()

df[["Branch", "City"]].head()

                     Branch       City
0        Pokhara - Lakeside    Pokhara
1    Butwal - Traffic Chowk     Butwal
2  Bhaktapur - Suryabinayak  Bhaktapur
3      Kathmandu - New Road  Kathmandu
4    Butwal - Traffic Chowk     Butwal

# Recalculate Total Amount

In [36]:
df["TotalAmount"] = df["Quantity"] * df["UnitPrice"] # recalculate the "TotalAmount" column based on "Quantity" and "UnitPrice" to ensure accuracy

df.head() # display the first few rows of the DataFrame to verify the changes

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod,Year,Month,MonthName,Day,Weekday,City
0,TXN101590,2025-05-19,CUST1100,Sujan Shrestha,Pokhara - Lakeside,Bakery,Chocolate Cake Slice,2,171.29,342.58,Khalti,2025,5,May,19,Monday,Pokhara
1,TXN103282,2025-03-07,CUST1005,Milan Lama,Butwal - Traffic Chowk,Personal Care,Dove Soap,3,149.59,448.77,eSewa,2025,3,March,7,Friday,Butwal
2,TXN103539,2025-10-05,CUST1130,Alina Rai,Bhaktapur - Suryabinayak,Apparel,Winter Jacket,4,2794.25,11177.00,Khalti,2025,10,October,5,Sunday,Bhaktapur
3,TXN102479,2025-11-12,CUST1057,Neha Karki,Kathmandu - New Road,Household,Surf Excel 1kg,4,399.62,1598.48,Cash,2025,11,November,12,Wednesday,Kathmandu
4,TXN104408,2025-10-09,CUST1005,Milan Lama,Butwal - Traffic Chowk,Beverages,Gorkha Beer (6-pack),2,281.01,562.02,eSewa,2025,10,October,9,Thursday,Butwal