# Import libraries

In [1]:
import pandas as pd

# Load dataset

In [2]:
df = pd.read_csv("nepal_bank_transactions.csv")

# Top 5 Rows, and Top 5 Column

In [3]:
print(df.head())
print("-" * 50)
print(df.columns)
print("-" * 50)
print(df.tail())
print("-" * 50)

  transaction_id        date      time       branch_name   district  \
0     TXN0000001  2024-01-01  00:43:34     New Baneshwor  Kathmandu
1     TXN0000002  2024-01-01  01:04:46  Dhangadhi Branch    Kailali
2     TXN0000003  2024-01-01  06:41:33    Hetauda Branch  Makwanpur
3     TXN0000004  2024-01-01  07:46:42     Butwal Branch  Rupandehi
4     TXN0000005  2024-01-01  08:44:14   Janakpur Branch   Dhanusha

            channel    transaction_type    card_type account_type  amount_npr  \
0               ATM      Mini Statement  Credit Card      Current        0.00
1  Internet Banking  Statement Download          NaN      Savings        0.00
2               ATM          PIN Change   Debit Card      Savings        0.00
3    Mobile Banking       Fund Transfer          NaN      Savings    97651.24
4               ATM      Mini Statement   Debit Card      Savings        0.00

   response_code response_message transaction_status  customer_age  \
0              0         Approved            Success          26.0
1              0         Approved            Success          30.0
2              0         Approved            Success          58.0
3              0         Approved            Success          56.0
4              0         Approved            Success          37.0

  customer_gender  processing_time_ms
0          Female                1322
1             NaN                 711
2          Female                1633
3          Female                 816
4            Male                1168
--------------------------------------------------
Index(['transaction_id', 'date', 'time', 'branch_name', 'district', 'channel',
       'transaction_type', 'card_type', 'account_type', 'amount_npr',
       'response_code', 'response_message', 'transaction_status',
       'customer_age', 'customer_gender', 'processing_time_ms'],
      dtype='str')
--------------------------------------------------
     transaction_id        date      time       branch_name   district  \
6055     TXN0005996  2024-12-31  17:47:21    Kathmandu Main  Kathmandu
6056     TXN0005997  2024-12-31  18:22:58  Dhangadhi Branch    Kailali
6057     TXN0005998  2024-12-31  19:45:09    Birgunj Branch      Parsa
6058     TXN0005999  2024-12-31  21:00:21     New Baneshwor  Kathmandu
6059     TXN0006000  2024-12-31  22:32:17     Butwal Branch  Rupandehi

             channel transaction_type   card_type account_type  amount_npr  \
6055  Mobile Banking  Balance Inquiry         NaN      Savings        0.00
6056             ATM  Cash Withdrawal  Debit Card      Savings     3000.00
6057  Mobile Banking    Fund Transfer         NaN      Savings    86174.23
6058             ATM  Cash Withdrawal  Debit Card      Savings     1000.00
6059  Mobile Banking       QR Payment         NaN      Savings     4014.87

      response_code response_message transaction_status  customer_age  \
6055              0         Approved            Success          38.0
6056              0         Approved            Success          18.0
6057              0         Approved            Success          33.0
6058              0         Approved            Success          41.0
6059             55    Incorrect PIN           Reversed          18.0

     customer_gender  processing_time_ms
6055          Female                 401
6056          Female                 970
6057            Male                 435
6058            Male                 901
6059          Female                 651
--------------------------------------------------

# Number of rows, and column

In [4]:
print(df.shape)

(6060, 16)

# General statistical analysis

In [5]:
print(df.info())
print("-" * 50)
print(df.describe())
print("-" * 50)
print(df.describe(include='all'))

<class 'pandas.DataFrame'>
RangeIndex: 6060 entries, 0 to 6059
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      6060 non-null   str
 1   date                6060 non-null   str
 2   time                6060 non-null   str
 3   branch_name         6060 non-null   str
 4   district            6060 non-null   str
 5   channel             6060 non-null   str
 6   transaction_type    6060 non-null   str
 7   card_type           3461 non-null   str
 8   account_type        6060 non-null   str
 9   amount_npr          6060 non-null   float64
 10  response_code       6060 non-null   int64
 11  response_message    6060 non-null   str
 12  transaction_status  6060 non-null   str
 13  customer_age        5941 non-null   float64
 14  customer_gender     5968 non-null   str
 15  processing_time_ms  6060 non-null   int64
dtypes: float64(2), int64(2), str(12)
memory usage: 757.6 KB
None
--------------------------------------------------
          amount_npr  response_code  customer_age  processing_time_ms
count    6060.000000    6060.000000   5941.000000         6060.000000
mean     8586.476797       6.142244     34.737755          835.182508
std     20667.251508      19.742012     11.414471          425.068837
min    -20000.000000       0.000000      0.000000           80.000000
25%         0.000000       0.000000     26.000000          524.000000
50%      1000.000000       0.000000     34.000000          754.000000
75%      7306.665000       0.000000     42.000000         1093.000000
max    198498.260000      96.000000    150.000000         2479.000000
--------------------------------------------------
       transaction_id        date      time       branch_name   district  \
count            6060        6060      6060              6060       6060
unique           6000         366      5743                45         13
top        TXN0000009  2024-04-05  10:25:05  Bhaktapur Branch  Kathmandu
freq                2          38         3               416        816
mean              NaN         NaN       NaN               NaN        NaN
std               NaN         NaN       NaN               NaN        NaN
min               NaN         NaN       NaN               NaN        NaN
25%               NaN         NaN       NaN               NaN        NaN
50%               NaN         NaN       NaN               NaN        NaN
75%               NaN         NaN       NaN               NaN        NaN
max               NaN         NaN       NaN               NaN        NaN

       channel transaction_type   card_type account_type     amount_npr  \
count     6060             6060        3461         6060    6060.000000
unique      10               13           3            3            NaN
top        ATM  Balance Inquiry  Debit Card      Savings            NaN
freq      2347             1040        2791         4758            NaN
mean       NaN              NaN         NaN          NaN    8586.476797
std        NaN              NaN         NaN          NaN   20667.251508
min        NaN              NaN         NaN          NaN  -20000.000000
25%        NaN              NaN         NaN          NaN       0.000000
50%        NaN              NaN         NaN          NaN    1000.000000
75%        NaN              NaN         NaN          NaN    7306.665000
max        NaN              NaN         NaN          NaN  198498.260000

        response_code response_message transaction_status  customer_age  \
count     6060.000000             6060               6060   5941.000000
unique            NaN                8                  4           NaN
top               NaN         Approved            Success           NaN
freq              NaN             5431               5431           NaN
mean         6.142244              NaN                NaN     34.737755
std         19.742012              NaN                NaN     11.414471
min          0.000000              NaN                NaN      0.000000
25%          0.000000              NaN                NaN     26.000000
50%          0.000000              NaN                NaN     34.000000
75%          0.000000              NaN                NaN     42.000000
max         96.000000              NaN                NaN    150.000000

       customer_gender  processing_time_ms
count             5968         6060.000000
unique               2                 NaN
top             Female                 NaN
freq              3094                 NaN
mean               NaN          835.182508
std                NaN          425.068837
min                NaN           80.000000
25%                NaN          524.000000
50%                NaN          754.000000
75%                NaN         1093.000000
max                NaN         2479.000000

# Selecting Columns, and rows

In [6]:
print(df["channel"].head())
print("-" * 50)
print(df[["branch_name", "channel", "amount_npr"]].head())

0                 ATM
1    Internet Banking
2                 ATM
3      Mobile Banking
4                 ATM
Name: channel, dtype: str
--------------------------------------------------
        branch_name           channel  amount_npr
0     New Baneshwor               ATM        0.00
1  Dhangadhi Branch  Internet Banking        0.00
2    Hetauda Branch               ATM        0.00
3     Butwal Branch    Mobile Banking    97651.24
4   Janakpur Branch               ATM        0.00

In [7]:
# .loc for label-based indexing
print(df.loc[0:5, ["branch_name"]])
print("-" * 50)
# .iloc for position-based indexing
print(df.iloc[0, 3])

        branch_name
0     New Baneshwor
1  Dhangadhi Branch
2    Hetauda Branch
3     Butwal Branch
4   Janakpur Branch
5  Dhangadhi Branch
--------------------------------------------------
New Baneshwor

In [8]:
df.loc[0:2, ["branch_name", "channel", "transaction_status"]]

        branch_name           channel transaction_status
0     New Baneshwor               ATM            Success
1  Dhangadhi Branch  Internet Banking            Success
2    Hetauda Branch               ATM            Success

# Filtering all ATM cash withdrawals

In [9]:
atm_withdrawals = df[(df["channel"] == "ATM") & (df["transaction_type"]=="Cash Withdrawal")]
print(atm_withdrawals.head())
print(f"ATM cash withdrawals: {len(atm_withdrawals)}")

    transaction_id        date      time       branch_name   district channel  \
32      TXN0000031  2024-01-03  02:48:19  Dhangadhi Branch    Kailali     ATM
49      TXN0000047  2024-01-04  04:01:12  Bharatpur Branch    Chitwan     ATM
51      TXN0000049  2024-01-04  08:50:02     New Baneshwor  Kathmandu     ATM
110     TXN0000108  2024-01-08  11:00:04  Bhaktapur Branch  Bhaktapur     ATM
115     TXN0000113  2024-01-08  14:52:36   Biratnagar Main     Morang     ATM

    transaction_type     card_type account_type  amount_npr  response_code  \
32   Cash Withdrawal    Debit Card      Current      3000.0              0
49   Cash Withdrawal    Debit Card      Savings      2500.0              0
51   Cash Withdrawal  Prepaid Card      Savings       500.0              0
110  Cash Withdrawal   Credit Card      Savings     15000.0              0
115  Cash Withdrawal   Credit Card      Savings      3000.0              0

    response_message transaction_status  customer_age customer_gender  \
32          Approved            Success          48.0          Female
49          Approved            Success          18.0          Female
51          Approved            Success          48.0          Female
110         Approved            Success          30.0          Female
115         Approved            Success          18.0            Male

     processing_time_ms
32                 1338
49                  551
51                 1087
110                 744
115                1295
ATM cash withdrawals: 586

In [10]:
df.columns

Index(['transaction_id', 'date', 'time', 'branch_name', 'district', 'channel',
       'transaction_type', 'card_type', 'account_type', 'amount_npr',
       'response_code', 'response_message', 'transaction_status',
       'customer_age', 'customer_gender', 'processing_time_ms'],
      dtype='str')

In [11]:
# All Failed, or reversed transactions
not_successful = df[df["transaction_status"] != "Success"]
print(f"Not Successful: {len(not_successful)} out of {len(df)} {len(not_successful)/len(df):.1%}")
not_successful["transaction_status"].value_counts()

Not Successful: 629 out of 6060 10.4%

transaction_status
Timeout     223
Failed      209
Reversed    197
Name: count, dtype: int64

In [12]:
# High-value fund trsanfers
large_transfers = df[(df["transaction_type"]=="Fund Transfer") & (df["amount_npr"]>5000)]
print(f"Large fund Transfer(> NPR 50,000): {len(large_transfers)}")

Large fund Transfer(> NPR 50,000): 559

# Sorting

In [13]:
df.sort_values("amount_npr", ascending=False).head(10)[
    ["transaction_id", "branch_name", "transaction_type", "amount_npr", "transaction_status"]
]

,transaction_id,branch_name,transaction_type,amount_npr,transaction_status
5500,TXN0005445,Dharan Branch,Cash Deposit,198498.26,Success
1621,TXN0001605,New Baneshwor,Cash Deposit,194948.77,Success
252,TXN0000249,Pokhara Lakeside,Cash Deposit,193797.93,Success
103,TXN0000101,Birgunj Branch,Cash Deposit,183308.51,Success
5960,TXN0005901,Bharatpur Branch,Cash Deposit,177534.63,Success
713,TXN0000704,Lalitpur Branch,Cash Deposit,176521.96,Success
3175,TXN0003137,Biratnagar Main,Cash Deposit,173506.79,Reversed
5638,TXN0005581,Dhangadhi Branch,Cash Deposit,170886.57,Success
5593,TXN0005536,New Baneshwor,Cash Deposit,169814.80,Success
3748,TXN0003707,Hetauda Branch,Cash Deposit,161213.69,Success